version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    restart: always
    environment:
      - DATABASE_URL=mysql://user:password@mysql:3306/mydatabase
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist/frontend/browser:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend

volumes:
  mysql_data:
